# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Counterpoint Documentation
description: >- # this means to ignore newlines until "baseurl:"
  Counterpoint is a JavaScript/TypeScript library to help people develop beautiful 
  large-scale animated data visualizations using HTML5 Canvas and WebGL.
baseurl: '/canvas-animation' # the subpath of your site, e.g. /blog
url: 'https://venkatesh-sivaraman.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: venkats_14
github_username: venkatesh-sivaraman/canvas-animation

# Build settings
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed

toc:
  enabled: true
  h_min: 1
  h_max: 3

collections:
  pages:
    output: true
    permalink: /:collection/:path/

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: base16

extra_css:
  - assets/custom_styles.css
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
